apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hospital-system
type: Opaque
data:
  # Base64 encoded values
  # user: postgres -> cG9zdGdyZXM=
  # password: postgres -> cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
